# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

registries:
  atos-actions:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{secrets.EVIDEN_ACTIONS_TOKEN}}
  eviden-parallel:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{secrets.EVIDEN_PARALLEL_TOKEN}}

updates:
  - package-ecosystem: 'npm'
    directory: '/'
    registries: '*'
    schedule:
      interval: 'daily'
      time: '00:00'
      timezone: 'Europe/Berlin'
    groups:
      astro:
        patterns:
          - 'astro'
          - 'astro-*'
          - '@astrojs/*'
      commitlint:
        patterns:
          - '@commitlint/*'
      playwright:
        patterns:
          - 'playwright*'
          - '@playwright/*'
      sharp:
        patterns:
          - 'sharp'
          - 'sharp-cli'

  - package-ecosystem: 'github-actions'
    directory: '/'
    registries: '*'
    schedule:
      interval: 'daily'
      time: '00:00'
      timezone: 'Europe/Berlin'
