# This is the workflow to lint the source code
name: Test

# Controls when the action will run.
on:
  # Allows you to call this workflow from other workflows
  workflow_call:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  read-playwright-version:
    name: 'ğŸ·ï¸ Read Playwright Version'
    runs-on: [self-hosted, linux]
    outputs:
      playwright-version: ${{ steps.get_playwright_version.outputs.playwright-version }}
    steps:
      - name: 'â˜ï¸ Checkout repository'
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.workflow_run.head_sha || github.event.pull_request.head.sha }}

      - id: get_playwright_version
        uses: atos-actions/get-playwright-version@v1

  build:
    name: 'ğŸ› ï¸ Test Code'
    runs-on: [self-hosted, linux]
    needs: read-playwright-version
    container: mcr.microsoft.com/playwright:${{ needs.read-playwright-version.outputs.playwright-version }} # Provide browser instances for test runners

    permissions:
      contents: read
      packages: read

    steps:
      - name: 'â˜ï¸ Checkout repository'
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.workflow_run.head_sha || github.event.pull_request.head.sha }}

      - name: 'â›“ï¸ Install dependencies'
        uses: atos-actions/npm-ci@v1
        with:
          npm_proxy: ${{ vars.NPM_PROXY }}
          private_registry_url: https://npm.pkg.github.com/
          private_registry_scope: '@eviden-parallel'
          token: ${{ secrets.NPM_TOKEN || secrets.GITHUB_TOKEN }}

      - name: 'ğŸ“ Download build output'
        uses: atos-actions/download-artifact@v2
        with:
          name: build

      - name: 'ğŸŒ Update browsers'
        run: npx playwright install

      - name: 'ğŸ§« Run tests'
        run: npm run test --if-present

      - name: 'ğŸ“¤ Upload test results'
        uses: actions/upload-artifact@v6 # TODO: Replace with atos-actions/upload-artifact when urn-id is supported in download-artifact
        with:
          name: test-results
          path: test-results
