# This is the workflow to validate a PR
#
name: Lint Pull Request

on:
  # Allows you to call this workflow from other workflows
  workflow_call:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  pr-lint:
    name: "üïµÔ∏è‚Äç‚ôÇÔ∏è Lint Commit Message"
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      # check for the most recent release: https://github.com/Namchee/conventional-pr/releases
      - name: "‚úÖ Lint PR"
        uses: Namchee/conventional-pr@v0.15.6
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
          label: "‚ÅâÔ∏è invalid"
          branch_pattern: ""
          issue: false
          message: |
            This Pull Request doesn't follow the contributing guidelines
